# SPDX-License-Identifier: GPL-3.0-only
import json
import logging
from collections import UserDict
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from hermeto.core.errors import InvalidLockfileFormat, UnexpectedFormat
from hermeto.core.package_managers.maven.utils import get_checksum_algorithm

log = logging.getLogger(__name__)

_REQUIRED_LOCKFILE_FIELDS = ("groupId", "artifactId", "version")
_REQUIRED_ARTIFACT_FIELDS = (
    "resolved",
    "groupId",
    "artifactId",
    "version",
    "checksumAlgorithm",
    "checksum",
)


class MavenLockfile:
    """Class representing JSON lockfile for Maven."""

    def __init__(self, path: Path, data: dict[str, Any]) -> None:
        """Initialize a MavenLockfile object."""
        self.path = path
        self.data = data

    @classmethod
    def from_file(cls, path: Path) -> "MavenLockfile":
        """Create a MavenLockfile object from the provided path."""
        try:
            with path.open() as f:
                data = json.load(f)
        except FileNotFoundError:
            raise
        except json.JSONDecodeError as e:
            raise InvalidLockfileFormat(
                path,
                f"invalid JSON: {e}",
                solution="Ensure lockfile.json contains valid JSON. "
                "Regenerate with: mvn io.github.chains-project:maven-lockfile:generate",
            ) from e

        missing = [f for f in _REQUIRED_LOCKFILE_FIELDS if f not in data]
        if missing:
            raise InvalidLockfileFormat(
                path,
                f"missing required fields: {', '.join(missing)}",
                solution="The lockfile appears incomplete. "
                "Regenerate with: mvn io.github.chains-project:maven-lockfile:generate",
            )

        lock_version = data.get("lockFileVersion")
        if lock_version is not None and (not isinstance(lock_version, int) or lock_version != 1):
            raise InvalidLockfileFormat(
                path,
                f"unsupported lockFileVersion: {lock_version} (expected 1)",
                solution="This lockfile was generated by a newer maven-lockfile plugin. "
                "Please update hermeto or regenerate with a compatible plugin version.",
            )

        return cls(path, data)


class MavenArtifact(UserDict):
    """Class representing a Maven artifact to download."""

    url: str
    group_id: str
    artifact_id: str
    version: str
    checksum_algorithm: str
    checksum: str

    def __init__(self, data: dict[str, Any]) -> None:
        """Initialize a MavenArtifact object."""
        missing = [f for f in _REQUIRED_ARTIFACT_FIELDS if f not in data]
        if missing:
            artifact_hint = data.get("artifactId", data.get("groupId", "unknown"))
            raise UnexpectedFormat(
                f"Maven artifact {artifact_hint!r} is missing required fields: {', '.join(missing)}",
                solution="The lockfile contains an incomplete artifact entry. "
                "Regenerate with: mvn io.github.chains-project:maven-lockfile:generate",
            )

        self.url = data["resolved"]
        self.group_id = data["groupId"]
        self.artifact_id = data["artifactId"]
        self.version = data["version"]
        self.checksum_algorithm = data["checksumAlgorithm"]
        self.checksum = data["checksum"]
        self.algorithm = get_checksum_algorithm(data["checksumAlgorithm"])
        self.classifier = data.get("classifier")
        self.artifact_type = data.get("type")
        super().__init__(data)

    @property
    def filename(self) -> str:
        """Get the filename of the artifact."""
        parsed_url = urlparse(self.url)
        return Path(parsed_url.path).name

    @property
    def artifact_relative_dir(self) -> Path:
        """Get the relative artifact directory."""
        group_dir = self.group_id.replace(".", "/")
        return Path(group_dir) / self.artifact_id / self.version


_MAX_TREE_DEPTH = 100


def _is_reactor_artifact(entry: dict[str, Any]) -> bool:
    """Return True if the entry is a reactor artifact (resolved URL present but empty)."""
    return "resolved" in entry and not entry["resolved"]


def _log_skipped_reactor(kind: str, entry: dict[str, Any]) -> None:
    log.info(
        "Skipping reactor %s %s:%s:%s (built from source, no remote URL)",
        kind,
        entry.get("groupId", "?"),
        entry.get("artifactId", "?"),
        entry.get("version", "?"),
    )


def _parse_dependency_tree(
    dependencies: list[MavenArtifact], children: list[dict[str, Any]]
) -> None:
    """Parse dependency tree iteratively with depth cap and included filtering."""
    stack: list[tuple[dict[str, Any], int]] = [(c, 0) for c in reversed(children)]
    while stack:
        child, depth = stack.pop()
        if depth > _MAX_TREE_DEPTH:
            raise InvalidLockfileFormat(
                "lockfile.json",
                f"dependency tree exceeds maximum depth of {_MAX_TREE_DEPTH}",
                solution="The lockfile may contain circular references. "
                "Regenerate with: mvn io.github.chains-project:maven-lockfile:generate",
            )
        if _is_reactor_artifact(child):
            _log_skipped_reactor("dependency", child)
        elif child.get("included", True):
            dependencies.append(MavenArtifact(child))
        # Always recurse: a reactor/excluded node's children may be external deps
        for grandchild in reversed(child.get("children", [])):
            stack.append((grandchild, depth + 1))


def _parse_bom_tree(boms: list[MavenArtifact], children: list[dict[str, Any]]) -> None:
    """Parse BOM tree iteratively with depth cap."""
    stack: list[tuple[dict[str, Any], int]] = [(c, 0) for c in reversed(children)]
    while stack:
        child, depth = stack.pop()
        if depth > _MAX_TREE_DEPTH:
            raise InvalidLockfileFormat(
                "lockfile.json",
                f"BOM tree exceeds maximum depth of {_MAX_TREE_DEPTH}",
                solution="The lockfile may contain circular references. "
                "Regenerate with: mvn io.github.chains-project:maven-lockfile:generate",
            )
        if _is_reactor_artifact(child):
            _log_skipped_reactor("BOM", child)
            continue
        boms.append(MavenArtifact(child))
        for grandchild in reversed(child.get("boms", [])):
            stack.append((grandchild, depth + 1))


def parse_maven_dependencies(lockfile: MavenLockfile) -> list[MavenArtifact]:
    """Parse dependencies from the lockfile to a flat list."""
    dependencies: list[MavenArtifact] = []
    _parse_dependency_tree(dependencies, lockfile.data.get("dependencies", []))
    return dependencies


def parse_maven_plugins(lockfile: MavenLockfile) -> list[MavenArtifact]:
    """Parse plugins from the lockfile to a flat list."""
    plugins: list[MavenArtifact] = []
    dependencies: list[MavenArtifact] = []
    for plugin in lockfile.data.get("mavenPlugins", []):
        if _is_reactor_artifact(plugin):
            _log_skipped_reactor("plugin", plugin)
        else:
            plugins.append(MavenArtifact(plugin))
        _parse_dependency_tree(dependencies, plugin.get("dependencies", []))

    return plugins + dependencies


def parse_maven_boms(dependencies: list[MavenArtifact]) -> list[MavenArtifact]:
    """Parse BOMs from the lockfile to a flat list."""
    boms: list[MavenArtifact] = []
    for dependency in dependencies:
        _parse_bom_tree(boms, dependency.get("boms", []))

    return boms


def parse_maven_extensions(lockfile: MavenLockfile) -> list[MavenArtifact]:
    """Parse extensions from the lockfile to a flat list."""
    extensions: list[MavenArtifact] = []
    for ext in lockfile.data.get("mavenExtensions", []):
        if _is_reactor_artifact(ext):
            _log_skipped_reactor("extension", ext)
        else:
            extensions.append(MavenArtifact(ext))
    return extensions
